import { LeaderboardEntry } from "../types";

export const MOCK_LEADERBOARD_ENTRIES: LeaderboardEntry[] = [
  {
    "rank": 1,
    "userId": "mock-1",
    "username": "puttipong.j@one.th",
    "nameTh": "พุฒิพงศ์ จันทพันธ์",
    "nameEn": "Puttipong Jantapan",
    "avatarUrl": "",
    "level": 3,
    "totalExp": 300,
    "rating": 4.5,
    "questsCompleted": 6,
    "totalPointsEarned": 1500
  },
  {
    "rank": 2,
    "userId": "e60750f0-498c-4f95-9909-3bd3745dc414",
    "username": "chanachon.pccwlk@gmail.com",
    "nameTh": "ชนชน ปรีชาชวลิตกุล",
    "nameEn": "Chanachon Preechachawalitkool",
    "avatarUrl": "",
    "level": 2,
    "totalExp": 250,
    "rating": 4.25,
    "questsCompleted": 5,
    "totalPointsEarned": 0
  },
  {
    "rank": 3,
    "userId": "mock-3",
    "username": "sorawit.t@one.th",
    "nameTh": "สรวิศ เต่าทอง",
    "nameEn": "Sorawit Taothong",
    "avatarUrl": "",
    "level": 1,
    "totalExp": 200,
    "rating": 3.0,
    "questsCompleted": 0,
    "totalPointsEarned": 0
  },
  {
    rank: 4,
    userId: "mock-4",
    username: "nattapon.k@one.th",
    nameTh: "ณัฐพล เกิดผล",
    nameEn: "Nattapon Kerdphol",
    avatarUrl: "",
    level: 14,
    totalExp: 180,
    rating: 4.5,
    questsCompleted: 7,
    totalPointsEarned: 1100
  },
  {
    rank: 5,
    userId: "mock-5",
    username: "thanawat.s@one.th",
    nameTh: "ธนวัฒน์ สุขสำราญ",
    nameEn: "Thanawat Suksamran",
    avatarUrl: "",
    level: 12,
    totalExp: 160,
    rating: 4.0,
    questsCompleted: 6,
    totalPointsEarned: 950
  },
  {
    rank: 6,
    userId: "mock-6",
    username: "preecha.c@one.th",
    nameTh: "ปรีชา ชาญเจริญ",
    nameEn: "Preecha Chancharoen",
    avatarUrl: "",
    level: 11,
    totalExp: 140,
    rating: 3.8,
    questsCompleted: 5,
    totalPointsEarned: 800
  },
  {
    rank: 7,
    userId: "mock-7",
    username: "anucha.p@one.th",
    nameTh: "อนุชา ปัญญา",
    nameEn: "Anucha Panya",
    avatarUrl: "",
    level: 10,
    totalExp: 120,
    rating: 4.1,
    questsCompleted: 5,
    totalPointsEarned: 750
  },
  {
    rank: 8,
    userId: "mock-8",
    username: "somchai.m@one.th",
    nameTh: "สมชาย มั่นคง",
    nameEn: "Somchai Mankong",
    avatarUrl: "",
    level: 9,
    totalExp: 100,
    rating: 3.5,
    questsCompleted: 4,
    totalPointsEarned: 600
  },
  {
    rank: 9,
    userId: "mock-9",
    username: "vitor.h@one.th",
    nameTh: "วิทูรย์ หรรษา",
    nameEn: "Vitoon Hansa",
    avatarUrl: "",
    level: 8,
    totalExp: 80,
    rating: 3.9,
    questsCompleted: 3,
    totalPointsEarned: 500
  },
  {
    rank: 10,
    userId: "mock-10",
    username: "kitti.p@one.th",
    nameTh: "กิตติพงษ์",
    nameEn: "Kittipong",
    avatarUrl: "",
    level: 7,
    totalExp: 50,
    rating: 3.8,
    questsCompleted: 2,
    totalPointsEarned: 400
  }
];
